name: Docker Flow Frontend

on:
  push:
    branches: [Dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dockerhub login
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
      run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
    - name: docker build image
      run: docker build -t kristinakalinchuk/vteams-frontend .
    - name: docker push image
      run: docker push kristinakalinchuk/vteams-frontend
